# Multi-Seed Experiments Job Configuration
# Usage: python gpu_scheduler.py --job-file jobs_multi_seed.yaml --min-memory 8000 --max-util 30

jobs:
  # CIFAR-100 α=0.05 - Seed 42
  - name: "CIFAR100_a005_FedAvg_seed42"
    config: "configs/CIFAR100_alpha0.05.yaml"
    algorithm: "FedAvg"
    log_path: "logs/multi_seed/CIFAR100_a005_FedAvg_seed42.log"
    extra_args:
      seed: 42
  
  - name: "CIFAR100_a005_FedETF_seed42"
    config: "configs/CIFAR100_alpha0.05.yaml"
    algorithm: "FedETF"
    log_path: "logs/multi_seed/CIFAR100_a005_FedETF_seed42.log"
    extra_args:
      seed: 42
  
  - name: "CIFAR100_a005_OursV7_seed42"
    config: "configs/CIFAR100_alpha0.05.yaml"
    algorithm: "OursV7"
    log_path: "logs/multi_seed/CIFAR100_a005_OursV7_seed42.log"
    extra_args:
      seed: 42
  
  - name: "CIFAR100_a005_OursV14_seed42"
    config: "configs/CIFAR100_alpha0.05.yaml"
    algorithm: "OursV14"
    log_path: "logs/multi_seed/CIFAR100_a005_OursV14_seed42.log"
    extra_args:
      seed: 42
  
  # CIFAR-100 α=0.05 - Seed 100
  - name: "CIFAR100_a005_FedAvg_seed100"
    config: "configs/CIFAR100_alpha0.05.yaml"
    algorithm: "FedAvg"
    log_path: "logs/multi_seed/CIFAR100_a005_FedAvg_seed100.log"
    extra_args:
      seed: 100
  
  - name: "CIFAR100_a005_FedETF_seed100"
    config: "configs/CIFAR100_alpha0.05.yaml"
    algorithm: "FedETF"
    log_path: "logs/multi_seed/CIFAR100_a005_FedETF_seed100.log"
    extra_args:
      seed: 100
  
  - name: "CIFAR100_a005_OursV7_seed100"
    config: "configs/CIFAR100_alpha0.05.yaml"
    algorithm: "OursV7"
    log_path: "logs/multi_seed/CIFAR100_a005_OursV7_seed100.log"
    extra_args:
      seed: 100
  
  - name: "CIFAR100_a005_OursV14_seed100"
    config: "configs/CIFAR100_alpha0.05.yaml"
    algorithm: "OursV14"
    log_path: "logs/multi_seed/CIFAR100_a005_OursV14_seed100.log"
    extra_args:
      seed: 100
  
  # CIFAR-100 α=0.05 - Seed 2023
  - name: "CIFAR100_a005_FedAvg_seed2023"
    config: "configs/CIFAR100_alpha0.05.yaml"
    algorithm: "FedAvg"
    log_path: "logs/multi_seed/CIFAR100_a005_FedAvg_seed2023.log"
    extra_args:
      seed: 2023
  
  - name: "CIFAR100_a005_FedETF_seed2023"
    config: "configs/CIFAR100_alpha0.05.yaml"
    algorithm: "FedETF"
    log_path: "logs/multi_seed/CIFAR100_a005_FedETF_seed2023.log"
    extra_args:
      seed: 2023
  
  - name: "CIFAR100_a005_OursV7_seed2023"
    config: "configs/CIFAR100_alpha0.05.yaml"
    algorithm: "OursV7"
    log_path: "logs/multi_seed/CIFAR100_a005_OursV7_seed2023.log"
    extra_args:
      seed: 2023
  
  - name: "CIFAR100_a005_OursV14_seed2023"
    config: "configs/CIFAR100_alpha0.05.yaml"
    algorithm: "OursV14"
    log_path: "logs/multi_seed/CIFAR100_a005_OursV14_seed2023.log"
    extra_args:
      seed: 2023
  
  # SVHN α=0.05 - Seed 42
  - name: "SVHN_a005_FedAvg_seed42"
    config: "configs/SVHN_alpha0.05.yaml"
    algorithm: "FedAvg"
    log_path: "logs/multi_seed/SVHN_a005_FedAvg_seed42.log"
    extra_args:
      seed: 42
  
  - name: "SVHN_a005_FedETF_seed42"
    config: "configs/SVHN_alpha0.05.yaml"
    algorithm: "FedETF"
    log_path: "logs/multi_seed/SVHN_a005_FedETF_seed42.log"
    extra_args:
      seed: 42
  
  - name: "SVHN_a005_OursV7_seed42"
    config: "configs/SVHN_alpha0.05.yaml"
    algorithm: "OursV7"
    log_path: "logs/multi_seed/SVHN_a005_OursV7_seed42.log"
    extra_args:
      seed: 42
  
  - name: "SVHN_a005_OursV14_seed42"
    config: "configs/SVHN_alpha0.05.yaml"
    algorithm: "OursV14"
    log_path: "logs/multi_seed/SVHN_a005_OursV14_seed42.log"
    extra_args:
      seed: 42
  
  # SVHN α=0.05 - Seed 100
  - name: "SVHN_a005_FedAvg_seed100"
    config: "configs/SVHN_alpha0.05.yaml"
    algorithm: "FedAvg"
    log_path: "logs/multi_seed/SVHN_a005_FedAvg_seed100.log"
    extra_args:
      seed: 100
  
  - name: "SVHN_a005_FedETF_seed100"
    config: "configs/SVHN_alpha0.05.yaml"
    algorithm: "FedETF"
    log_path: "logs/multi_seed/SVHN_a005_FedETF_seed100.log"
    extra_args:
      seed: 100
  
  - name: "SVHN_a005_OursV7_seed100"
    config: "configs/SVHN_alpha0.05.yaml"
    algorithm: "OursV7"
    log_path: "logs/multi_seed/SVHN_a005_OursV7_seed100.log"
    extra_args:
      seed: 100
  
  - name: "SVHN_a005_OursV14_seed100"
    config: "configs/SVHN_alpha0.05.yaml"
    algorithm: "OursV14"
    log_path: "logs/multi_seed/SVHN_a005_OursV14_seed100.log"
    extra_args:
      seed: 100
  
  # SVHN α=0.05 - Seed 2023
  - name: "SVHN_a005_FedAvg_seed2023"
    config: "configs/SVHN_alpha0.05.yaml"
    algorithm: "FedAvg"
    log_path: "logs/multi_seed/SVHN_a005_FedAvg_seed2023.log"
    extra_args:
      seed: 2023
  
  - name: "SVHN_a005_FedETF_seed2023"
    config: "configs/SVHN_alpha0.05.yaml"
    algorithm: "FedETF"
    log_path: "logs/multi_seed/SVHN_a005_FedETF_seed2023.log"
    extra_args:
      seed: 2023
  
  - name: "SVHN_a005_OursV7_seed2023"
    config: "configs/SVHN_alpha0.05.yaml"
    algorithm: "OursV7"
    log_path: "logs/multi_seed/SVHN_a005_OursV7_seed2023.log"
    extra_args:
      seed: 2023
  
  - name: "SVHN_a005_OursV14_seed2023"
    config: "configs/SVHN_alpha0.05.yaml"
    algorithm: "OursV14"
    log_path: "logs/multi_seed/SVHN_a005_OursV14_seed2023.log"
    extra_args:
      seed: 2023
